# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listOne.ui'
#
# Created by: PyQt5 UI Code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        font = QtGui.QFont()
        font.setItalic(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listOne_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listOne_4.sizePolicy().hasHeightForWidth())
        self.listOne_4.setSizePolicy(sizePolicy)
        self.listOne_4.setMinimumSize(QtCore.QSize(200, 70))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listOne_4.setFont(font)
        self.listOne_4.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(5, 171, 194);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\WorkSpace\\VIDAS\\3QT\\UI\\icon\\4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listOne_4.setIcon(icon)
        self.listOne_4.setIconSize(QtCore.QSize(40, 40))
        self.listOne_4.setObjectName("listOne_4")
        self.gridLayout.addWidget(self.listOne_4, 1, 1, 1, 1)
        self.listOne_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listOne_2.sizePolicy().hasHeightForWidth())
        self.listOne_2.setSizePolicy(sizePolicy)
        self.listOne_2.setMinimumSize(QtCore.QSize(200, 70))
        self.listOne_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.listOne_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listOne_2.setFont(font)
        self.listOne_2.setMouseTracking(False)
        self.listOne_2.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(5, 171, 194);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\WorkSpace\\VIDAS\\3QT\\UI\\icon\\2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listOne_2.setIcon(icon1)
        self.listOne_2.setIconSize(QtCore.QSize(40, 40))
        self.listOne_2.setObjectName("listOne_2")
        self.gridLayout.addWidget(self.listOne_2, 0, 1, 1, 1)
        self.listOne_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.listOne_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listOne_1.sizePolicy().hasHeightForWidth())
        self.listOne_1.setSizePolicy(sizePolicy)
        self.listOne_1.setMinimumSize(QtCore.QSize(200, 70))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listOne_1.setFont(font)
        self.listOne_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.listOne_1.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(5, 171, 194);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\WorkSpace\\VIDAS\\3QT\\UI\\icon\\1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listOne_1.setIcon(icon2)
        self.listOne_1.setIconSize(QtCore.QSize(45, 45))
        self.listOne_1.setObjectName("listOne_1")
        self.gridLayout.addWidget(self.listOne_1, 0, 0, 1, 1)
        self.listOne_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listOne_3.sizePolicy().hasHeightForWidth())
        self.listOne_3.setSizePolicy(sizePolicy)
        self.listOne_3.setMinimumSize(QtCore.QSize(200, 70))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.listOne_3.setFont(font)
        self.listOne_3.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(5, 171, 194);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\WorkSpace\\VIDAS\\3QT\\UI\\icon\\3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listOne_3.setIcon(icon3)
        self.listOne_3.setIconSize(QtCore.QSize(30, 30))
        self.listOne_3.setObjectName("listOne_3")
        self.gridLayout.addWidget(self.listOne_3, 1, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 280, 801, 72))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(600, 70))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(5, 171, 194);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: pt \"宋体\";\n"
"    font: 20pt \"Adobe Devanagari\";\n"
"    border-radius: 30px;  \n"
"    border: 3px groove black;\n"
"    border-style: outset;\n"
"    /*按下时字向右移动4像素*/  \n"
"    padding-left:4px;\n"
"    /*按下时字向下移动4像素*/  \n"
"    padding-top:4px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\WorkSpace\\VIDAS\\3QT\\UI\\icon\\5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setShortcut("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listOne_4.setText(_translate("MainWindow", "系统设置"))
        self.listOne_2.setText(_translate("MainWindow", "历史记录"))
        self.listOne_1.setText(_translate("MainWindow", "荧光检疫"))
        self.listOne_3.setText(_translate("MainWindow", "检疫设置"))
        self.pushButton.setText(_translate("MainWindow", "电     源"))
